package view_control;

/* 
 * Copyright (C) 2019 Moisis Artemiadis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
import java.awt.Rectangle;
import model.functions.Utilities;
import view_control.IO.ErrorOutputStream;
import model.elements.MLClass;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.elements.DatasetImage;
import model.elements.BoundingBox;
import model.functions.ProjectManager;

/**
 *
 * @author Moisis Artemiadis
 */
public class GUIMain extends JFrame {

    /**
     * Creates new form TempCklass
     *
     */
    public GUIMain() {
        this.classesModel = new DefaultListModel();
        this.bboxModel = new DefaultListModel();
        this.clickStart = false;
        this.printStreamList.add(System.out);
        this.printStreamList.add(System.err);
        initComponents();
        this.printStreamList.add(new PrintStream(new ErrorOutputStream(this.tab01ErrorOutput)));
        this.printStreamList.add(new PrintStream(new ErrorOutputStream(this.tab02ErrorOutput)));
        this.printStreamList.add(new PrintStream(new ErrorOutputStream(this.tab03ErrorOutput)));
        newClassDialog.getRootPane().setDefaultButton(createClass);
        rectangles = new LinkedList<>();
        bBoxLabel = (BBoxJLabel) this.imageLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        newClassDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createClass = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        labelingTool = new javax.swing.JPanel();
        projectPathLabel = new javax.swing.JLabel();
        projectTextField = new javax.swing.JTextField();
        openProjectButton = new javax.swing.JButton();
        tab01ToolsSplitPane = new javax.swing.JSplitPane();
        tab01ErrScrollPane = new javax.swing.JScrollPane();
        tab01ErrorOutput = new javax.swing.JTextArea();
        labelingSplitPane = new javax.swing.JSplitPane();
        listsSplitPane = new javax.swing.JSplitPane();
        classesPane = new javax.swing.JPanel();
        classesLabel = new javax.swing.JLabel();
        classesScollPane = new javax.swing.JScrollPane();
        classesList = new javax.swing.JList<>(this.classesModel);
        labelsPane = new javax.swing.JPanel();
        labelsLabel = new javax.swing.JLabel();
        labelsScrollPane = new javax.swing.JScrollPane();
        labelsList = new javax.swing.JList<>(this.bboxModel);
        editingPane = new javax.swing.JPanel();
        prevImgButton = new javax.swing.JButton();
        nextImgButton = new javax.swing.JButton();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        imageLabel = new BBoxJLabel();
        imageRenumberingTab = new javax.swing.JPanel();
        numberingStartLabel = new javax.swing.JLabel();
        numberingStartTextField = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        tab02OpenFileBt = new javax.swing.JButton();
        tab02RunBt = new javax.swing.JButton();
        tab02ErrScrollPane = new javax.swing.JScrollPane();
        tab02ErrorOutput = new javax.swing.JTextArea();
        logParser = new javax.swing.JPanel();
        logFileLabel = new javax.swing.JLabel();
        logFileTextField = new javax.swing.JTextField();
        outputFileLabel = new javax.swing.JLabel();
        outputTextField = new javax.swing.JTextField();
        tab03OpenRFBt = new javax.swing.JButton();
        tab03OpenWFBt = new javax.swing.JButton();
        tab03RunBt = new javax.swing.JButton();
        paternIndexComboBox = new javax.swing.JComboBox<>();
        speratorLabel = new javax.swing.JLabel();
        seperatorComboBox = new javax.swing.JComboBox<>();
        yoloVerComboBox = new javax.swing.JComboBox<>();
        filterCheckBox = new javax.swing.JCheckBox();
        customSLabel = new javax.swing.JLabel();
        customSTF = new javax.swing.JTextField();
        tab03ErrScrollPane = new javax.swing.JScrollPane();
        tab03ErrorOutput = new javax.swing.JTextArea();
        imagePathFilesMaker = new javax.swing.JPanel();
        tab04ErrScrollPane = new javax.swing.JScrollPane();
        tab04ErrorOutput = new javax.swing.JTextArea();
        outputFileLabel1 = new javax.swing.JLabel();
        outputFileLabel2 = new javax.swing.JLabel();
        outputFileLabel3 = new javax.swing.JLabel();
        outputFileLabel4 = new javax.swing.JLabel();
        logFileTextField1 = new javax.swing.JTextField();
        logFileTextField2 = new javax.swing.JTextField();
        logFileTextField3 = new javax.swing.JTextField();
        logFileTextField4 = new javax.swing.JTextField();
        tab03OpenRFBt1 = new javax.swing.JButton();
        showLabels = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        fileChooser.setBackground(java.awt.Color.white);
        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\user\\Desktop"));
        fileChooser.setDialogTitle("choose");
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        newClassDialog.setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel2.setText("Give Classes name and number");

        jLabel3.setText("Class name");

        jLabel4.setText("Class num");

        createClass.setText("OK");
        createClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newClassDialogLayout = new javax.swing.GroupLayout(newClassDialog.getContentPane());
        newClassDialog.getContentPane().setLayout(newClassDialogLayout);
        newClassDialogLayout.setHorizontalGroup(
            newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClassDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newClassDialogLayout.createSequentialGroup()
                        .addGroup(newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newClassDialogLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createClass))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newClassDialogLayout.setVerticalGroup(
            newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClassDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createClass))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multi Tool");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getWindowIcon());

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        labelingTool.setAutoscrolls(true);

        projectPathLabel.setLabelFor(projectTextField);
        projectPathLabel.setText("Project Path");

        openProjectButton.setText("Open");
        openProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectButtonActionPerformed(evt);
            }
        });

        tab01ToolsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tab01ErrorOutput.setColumns(20);
        tab01ErrorOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab01ErrorOutput.setRows(5);
        tab01ErrScrollPane.setViewportView(tab01ErrorOutput);

        tab01ToolsSplitPane.setTopComponent(tab01ErrScrollPane);

        labelingSplitPane.setDividerLocation(300);
        labelingSplitPane.setMinimumSize(new java.awt.Dimension(200, 200));

        listsSplitPane.setDividerLocation(150);

        classesLabel.setLabelFor(classesScollPane);
        classesLabel.setText("Classes");

        classesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        classesList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classesListKeyPressed(evt);
            }
        });
        classesScollPane.setViewportView(classesList);

        javax.swing.GroupLayout classesPaneLayout = new javax.swing.GroupLayout(classesPane);
        classesPane.setLayout(classesPaneLayout);
        classesPaneLayout.setHorizontalGroup(
            classesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classesScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(classesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        classesPaneLayout.setVerticalGroup(
            classesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classesPaneLayout.createSequentialGroup()
                .addComponent(classesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classesScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
        );

        listsSplitPane.setRightComponent(classesPane);

        labelsLabel.setLabelFor(labelsScrollPane);
        labelsLabel.setText("Labels");

        labelsScrollPane.setViewportView(labelsList);

        javax.swing.GroupLayout labelsPaneLayout = new javax.swing.GroupLayout(labelsPane);
        labelsPane.setLayout(labelsPaneLayout);
        labelsPaneLayout.setHorizontalGroup(
            labelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(labelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        labelsPaneLayout.setVerticalGroup(
            labelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsPaneLayout.createSequentialGroup()
                .addComponent(labelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
        );

        listsSplitPane.setLeftComponent(labelsPane);

        labelingSplitPane.setLeftComponent(listsSplitPane);

        prevImgButton.setText("Prev");
        prevImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevImgButtonActionPerformed(evt);
            }
        });

        nextImgButton.setText("Next");
        nextImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextImgButtonActionPerformed(evt);
            }
        });

        xLabel.setText("x: ");

        yLabel.setText("y:");

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setToolTipText("");
        imageLabel.setAlignmentY(0.0F);
        imageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imageLabel.setDoubleBuffered(true);
        imageLabel.setMaximumSize(new java.awt.Dimension(512, 512));
        imageLabel.setMinimumSize(new java.awt.Dimension(512, 512));
        imageLabel.setName(""); // NOI18N
        imageLabel.setPreferredSize(new java.awt.Dimension(512, 512));
        imageLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelMouseMoved(evt);
            }
        });
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editingPaneLayout = new javax.swing.GroupLayout(editingPane);
        editingPane.setLayout(editingPaneLayout);
        editingPaneLayout.setHorizontalGroup(
            editingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editingPaneLayout.createSequentialGroup()
                        .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prevImgButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextImgButton))
                    .addGroup(editingPaneLayout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        editingPaneLayout.setVerticalGroup(
            editingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevImgButton)
                    .addComponent(nextImgButton)
                    .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        labelingSplitPane.setRightComponent(editingPane);

        tab01ToolsSplitPane.setRightComponent(labelingSplitPane);

        javax.swing.GroupLayout labelingToolLayout = new javax.swing.GroupLayout(labelingTool);
        labelingTool.setLayout(labelingToolLayout);
        labelingToolLayout.setHorizontalGroup(
            labelingToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelingToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openProjectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tab01ToolsSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );
        labelingToolLayout.setVerticalGroup(
            labelingToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelingToolLayout.createSequentialGroup()
                .addGroup(labelingToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(labelingToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openProjectButton))
                    .addComponent(projectPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab01ToolsSplitPane))
        );

        tabs.addTab("Labeling Tool", labelingTool);

        imageRenumberingTab.setAutoscrolls(true);

        numberingStartLabel.setLabelFor(numberingStartTextField);
        numberingStartLabel.setText("Renumbering Start");

        numberingStartTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        pathLabel.setLabelFor(pathTextField);
        pathLabel.setText("File Path");

        pathTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        tab02OpenFileBt.setText("Open");
        tab02OpenFileBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab02OpenFileBtOpenFileChooser(evt);
            }
        });

        tab02RunBt.setText("Run");
        tab02RunBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab02RunBtActionPerformed(evt);
            }
        });

        tab02ErrorOutput.setColumns(20);
        tab02ErrorOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab02ErrorOutput.setRows(5);
        tab02ErrScrollPane.setViewportView(tab02ErrorOutput);

        javax.swing.GroupLayout imageRenumberingTabLayout = new javax.swing.GroupLayout(imageRenumberingTab);
        imageRenumberingTab.setLayout(imageRenumberingTabLayout);
        imageRenumberingTabLayout.setHorizontalGroup(
            imageRenumberingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imageRenumberingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imageRenumberingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imageRenumberingTabLayout.createSequentialGroup()
                        .addComponent(numberingStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numberingStartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tab02OpenFileBt))
                    .addGroup(imageRenumberingTabLayout.createSequentialGroup()
                        .addComponent(tab02RunBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 823, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(tab02ErrScrollPane)
        );
        imageRenumberingTabLayout.setVerticalGroup(
            imageRenumberingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageRenumberingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imageRenumberingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberingStartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab02OpenFileBt, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberingStartTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tab02RunBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab02ErrScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
        );

        tabs.addTab("Image Renumbering Tool", imageRenumberingTab);

        logFileLabel.setLabelFor(logFileTextField);
        logFileLabel.setText("Log File Directory Path");
        logFileLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        logFileLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        logFileLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        logFileTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        outputFileLabel.setLabelFor(outputTextField);
        outputFileLabel.setText("Output File");
        outputFileLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        outputFileLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        outputFileLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        outputTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        tab03OpenRFBt.setText("Open");
        tab03OpenRFBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab03OpenRFBtActionPerformed(evt);
            }
        });

        tab03OpenWFBt.setText("Open");
        tab03OpenWFBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab03OpenWFBtActionPerformed(evt);
            }
        });

        tab03RunBt.setText("Run");
        tab03RunBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab03RunBtActionPerformed(evt);
            }
        });

        paternIndexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "match AVG loss lines", "match mAP lines", "match per class lines" }));
        paternIndexComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paternIndexComboBoxItemStateChanged(evt);
            }
        });
        paternIndexComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paternIndexComboBoxActionPerformed(evt);
            }
        });

        speratorLabel.setLabelFor(seperatorComboBox);
        speratorLabel.setText("Seperator:");
        speratorLabel.setToolTipText("");

        seperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Character[] {',',';'}));
        seperatorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seperatorComboBoxActionPerformed(evt);
            }
        });

        yoloVerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Utilities.NAMES));

        filterCheckBox.setText(checkBoxTexts[0]);

        customSLabel.setLabelFor(customSTF);
        customSLabel.setText("<html><p>Custom string to concat at the end of the file name:</p><html/>");

        tab03ErrorOutput.setColumns(20);
        tab03ErrorOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab03ErrorOutput.setRows(5);
        tab03ErrScrollPane.setViewportView(tab03ErrorOutput);

        javax.swing.GroupLayout logParserLayout = new javax.swing.GroupLayout(logParser);
        logParser.setLayout(logParserLayout);
        logParserLayout.setHorizontalGroup(
            logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logParserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab03ErrScrollPane)
                    .addGroup(logParserLayout.createSequentialGroup()
                        .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(logParserLayout.createSequentialGroup()
                                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tab03RunBt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(logParserLayout.createSequentialGroup()
                                        .addComponent(paternIndexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(filterCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(outputFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(logParserLayout.createSequentialGroup()
                                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(logParserLayout.createSequentialGroup()
                                        .addComponent(customSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(customSTF))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, logParserLayout.createSequentialGroup()
                                        .addComponent(speratorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(seperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yoloVerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tab03OpenRFBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tab03OpenWFBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        logParserLayout.setVerticalGroup(
            logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logParserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab03OpenRFBt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tab03OpenWFBt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paternIndexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterCheckBox))
                    .addComponent(speratorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seperatorComboBox)
                    .addComponent(yoloVerComboBox))
                .addGap(18, 18, 18)
                .addGroup(logParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tab03RunBt, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(customSLabel)
                    .addComponent(customSTF))
                .addGap(18, 18, 18)
                .addComponent(tab03ErrScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                .addContainerGap())
        );

        yoloVerComboBox.setSelectedIndex(1);

        tabs.addTab("Log Parser", logParser);

        tab04ErrorOutput.setColumns(20);
        tab04ErrorOutput.setRows(5);
        tab04ErrScrollPane.setViewportView(tab04ErrorOutput);

        outputFileLabel1.setLabelFor(outputTextField);
        outputFileLabel1.setText("Images & TXTs Parent Directory:");
        outputFileLabel1.setMaximumSize(new java.awt.Dimension(90, 14));
        outputFileLabel1.setMinimumSize(new java.awt.Dimension(90, 14));
        outputFileLabel1.setPreferredSize(new java.awt.Dimension(90, 14));

        outputFileLabel2.setLabelFor(outputTextField);
        outputFileLabel2.setText("Output File");
        outputFileLabel2.setMaximumSize(new java.awt.Dimension(90, 14));
        outputFileLabel2.setMinimumSize(new java.awt.Dimension(90, 14));
        outputFileLabel2.setPreferredSize(new java.awt.Dimension(90, 14));

        outputFileLabel3.setLabelFor(outputTextField);
        outputFileLabel3.setText("Output File");
        outputFileLabel3.setMaximumSize(new java.awt.Dimension(90, 14));
        outputFileLabel3.setMinimumSize(new java.awt.Dimension(90, 14));
        outputFileLabel3.setPreferredSize(new java.awt.Dimension(90, 14));

        outputFileLabel4.setLabelFor(outputTextField);
        outputFileLabel4.setText("Output File");
        outputFileLabel4.setMaximumSize(new java.awt.Dimension(90, 14));
        outputFileLabel4.setMinimumSize(new java.awt.Dimension(90, 14));
        outputFileLabel4.setPreferredSize(new java.awt.Dimension(90, 14));

        logFileTextField1.setMaximumSize(new java.awt.Dimension(6, 20));

        logFileTextField2.setMaximumSize(new java.awt.Dimension(6, 20));

        logFileTextField3.setMaximumSize(new java.awt.Dimension(6, 20));

        logFileTextField4.setMaximumSize(new java.awt.Dimension(6, 20));

        tab03OpenRFBt1.setText("Open");
        tab03OpenRFBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab03OpenRFBt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePathFilesMakerLayout = new javax.swing.GroupLayout(imagePathFilesMaker);
        imagePathFilesMaker.setLayout(imagePathFilesMakerLayout);
        imagePathFilesMakerLayout.setHorizontalGroup(
            imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePathFilesMakerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab04ErrScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePathFilesMakerLayout.createSequentialGroup()
                        .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePathFilesMakerLayout.createSequentialGroup()
                                .addComponent(outputFileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logFileTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePathFilesMakerLayout.createSequentialGroup()
                                .addComponent(outputFileLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logFileTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePathFilesMakerLayout.createSequentialGroup()
                                .addComponent(outputFileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logFileTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePathFilesMakerLayout.createSequentialGroup()
                                .addComponent(outputFileLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logFileTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tab03OpenRFBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        imagePathFilesMakerLayout.setVerticalGroup(
            imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePathFilesMakerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logFileTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab03OpenRFBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logFileTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logFileTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePathFilesMakerLayout.createSequentialGroup()
                        .addComponent(outputFileLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(imagePathFilesMakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logFileTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab04ErrScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("Image Path Files Maker", imagePathFilesMaker);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout showLabelsLayout = new javax.swing.GroupLayout(showLabels);
        showLabels.setLayout(showLabelsLayout);
        showLabelsLayout.setHorizontalGroup(
            showLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLabelsLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(725, Short.MAX_VALUE))
        );
        showLabelsLayout.setVerticalGroup(
            showLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLabelsLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(810, Short.MAX_VALUE))
        );

        tabs.addTab("Predicted Labels", showLabels);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab02OpenFileBtOpenFileChooser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab02OpenFileBtOpenFileChooser
        if (!pathTextField.getText().equals("") || !pathTextField.getText().equals(" ")) {
            File dir = new File(pathTextField.getText());
            if (dir.isDirectory()) {
                if (dir.exists()) {
                    fileChooser.setCurrentDirectory(dir);
                } else {
                    fileChooser.setCurrentDirectory(dir.getParentFile());
                }
            }
        }
        int ok = fileChooser.showOpenDialog(this);
        if (ok == fileChooser.APPROVE_OPTION) {
            //System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
            pathTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_tab02OpenFileBtOpenFileChooser

    private void tab02RunBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab02RunBtActionPerformed
        if ((numberingStartTextField.getText() == null || numberingStartTextField.getText().equals(""))
                || (pathTextField.getText() == null || pathTextField.getText().equals(""))) {
            JOptionPane.showMessageDialog(this,
                    "Inputs are not set.",
                    "Run Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int startNum = Integer.parseInt(numberingStartTextField.getText());
                Utilities.imageNumberings(startNum, pathTextField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                    "Renumbering Start Field is not a number",
                    "Run Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tab02RunBtActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        SwingUtilities.invokeLater(
                new Runnable() {
            public void run() {
                System.setErr(printStreamList.get(tabs.getSelectedIndex() + 2));
                System.setOut(printStreamList.get(tabs.getSelectedIndex() + 2));

            }
        });
    }//GEN-LAST:event_tabsStateChanged

    private void openProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectButtonActionPerformed
        if (projectTextField.getText() == null || projectTextField.getText().equals("")) {
            int ok = fileChooser.showOpenDialog(this);
            if (ok == fileChooser.APPROVE_OPTION) {
                projectTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
            }
        } else {
            manager = new ProjectManager(projectTextField.getText());
            loadClasses();
            loadNextImage();
        }
    }//GEN-LAST:event_openProjectButtonActionPerformed

    private void classesListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classesListKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_EQUALS) && ((evt.getModifiers() & KeyEvent.SHIFT_MASK) != 0)) {
            newClassDialog.setEnabled(true);
            newClassDialog.setVisible(newClassDialog.isEnabled());
            newClassDialog.setSize(355, 200);
        }
        /*else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            classesModel.remove(this.classesList.getSelectedIndex());
        }*/
    }//GEN-LAST:event_classesListKeyPressed

    private void createClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClassActionPerformed
        this.classesModel.addElement(new MLClass(jTextField1.getText(), Integer.parseInt(jTextField2.getText()), 0.0F, 0.0F, 0.0F));
        jTextField1.setText("");
        jTextField2.setText("");
        newClassDialog.setEnabled(false);
        newClassDialog.setVisible(newClassDialog.isEnabled());
    }//GEN-LAST:event_createClassActionPerformed

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        bBoxLabel.mousePressed(evt);
        clickStart = !clickStart;
        if (!clickStart) {
            if (!bBoxLabel.squaresIsEmpty()) {
                Rectangle r = bBoxLabel.getLastSq();
                bboxModel.addElement(new BoundingBox(r.x, r.y, r.x + r.width, r.y + r.width,
                        (this.classesList.getSelectedValue() != null) ? this.classesList.getSelectedValue() : new MLClass("aktinidio", 1), 1.0f));
            }
        }
    }//GEN-LAST:event_imageLabelMouseClicked

    private void imageLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseMoved
        bBoxLabel.mouseMoved(evt);
        xLabel.setText("x: " + bBoxLabel.getMouseX());
        yLabel.setText("y: " + bBoxLabel.getMouseY());
    }//GEN-LAST:event_imageLabelMouseMoved

    private void nextImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextImgButtonActionPerformed
        loadNextImage();
    }//GEN-LAST:event_nextImgButtonActionPerformed

    private void prevImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevImgButtonActionPerformed
        loadPreviousImage();
    }//GEN-LAST:event_prevImgButtonActionPerformed

    private void imageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseEntered
        bBoxLabel.mouseEntered();
    }//GEN-LAST:event_imageLabelMouseEntered

    private void imageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseExited
        bBoxLabel.mouseExited();
    }//GEN-LAST:event_imageLabelMouseExited

    private void tab03RunBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab03RunBtActionPerformed
        if ((logFileTextField.getText() == null || logFileTextField.getText().equals(""))
                || (outputTextField.getText() == null || outputTextField.getText().equals(""))) {
            JOptionPane.showMessageDialog(this,
                    "File path inputs are not set.",
                    "Run Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            Utilities.SEPERATOR = (char) seperatorComboBox.getSelectedItem();
            Utilities.CONCAT = customSTF.getText();
            Utilities.logParser(logFileTextField.getText(),
                    outputTextField.getText(),
                    paternIndexComboBox.getSelectedIndex(),
                    filterCheckBox.isSelected(),
                    yoloVerComboBox.getSelectedIndex());
        }
    }//GEN-LAST:event_tab03RunBtActionPerformed

    private void tab03OpenRFBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab03OpenRFBtActionPerformed
        if (!logFileTextField.getText().equals("") || !logFileTextField.getText().equals(" ")) {
            File dir = new File(logFileTextField.getText());
            if (dir.isDirectory()) {
                if (dir.exists()) {
                    fileChooser.setCurrentDirectory(dir);
                } else {
                    fileChooser.setCurrentDirectory(dir.getParentFile());
                }
            }
        }
        int ok = fileChooser.showOpenDialog(this);
        if (ok == fileChooser.APPROVE_OPTION) {
            logFileTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_tab03OpenRFBtActionPerformed

    private void paternIndexComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paternIndexComboBoxActionPerformed
        int index = paternIndexComboBox.getSelectedIndex();
        filterCheckBox.setText("<html><p>" + checkBoxTexts[index] + "</p></html>");
        if (index == 2) {
            JOptionPane.showMessageDialog(this,
                    "This match creates multiple files, point the output directory to a plain folder for easier management.",
                    "Match Classes Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_paternIndexComboBoxActionPerformed

    private void tab03OpenWFBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab03OpenWFBtActionPerformed
        if (!outputTextField.getText().equals("") || !outputTextField.getText().equals(" ")) {
            File dir = new File(outputTextField.getText());
            if (dir.isDirectory()) {
                if (dir.exists()) {
                    fileChooser.setCurrentDirectory(dir);
                } else {
                    fileChooser.setCurrentDirectory(dir.getParentFile());
                }
            }
        }
        int ok = fileChooser.showOpenDialog(this);
        if (ok == fileChooser.APPROVE_OPTION) {
            outputTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_tab03OpenWFBtActionPerformed

    private void paternIndexComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paternIndexComboBoxItemStateChanged
        System.out.println(paternIndexComboBox.getSelectedIndex());
    }//GEN-LAST:event_paternIndexComboBoxItemStateChanged

    private void tab03OpenRFBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab03OpenRFBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab03OpenRFBt1ActionPerformed

    private void seperatorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seperatorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seperatorComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if (info.getClassName().equals(UIManager.getSystemLookAndFeelClassName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMain().setVisible(true);
            }
        });
    }

    private void loadClasses() {
        ListIterator<MLClass> classes = manager.getClassIterator();
        while (classes.hasNext()) {
            classesModel.addElement(classes.next());
        }
    }

    private void loadNextImage() {
        bboxModel.clear();
        while (!rectangles.isEmpty()) {
            bBoxLabel.removeReactangle(rectangles.removeFirst());
        }
        DatasetImage data;
        if ((data = manager.nextElement()) != null) {
            this.imageLabel.setIcon(data.getImage());
            ListIterator<BoundingBox> bBoxes = data.getBBoxIterator();
            BoundingBox bBox;
            while (bBoxes.hasNext()) {
                bBox = bBoxes.next();
                bboxModel.addElement(bBox);
                rectangles.add(bBoxLabel.addReactangle(bBox.getBottomLeftPoint().x, bBox.getBottomLeftPoint().y,
                        bBox.getTopRightPoint().x, bBox.getTopRightPoint().y));
            }
        }

    }

    private void loadPreviousImage() {
        bboxModel.clear();
        DatasetImage data = manager.previousElement();
        this.imageLabel.setIcon(data.getImage());
        ListIterator<BoundingBox> bBoxes = data.getBBoxIterator();
        while (bBoxes.hasNext()) {
            bboxModel.addElement(bBoxes.next());
        }
    }

    private BufferedImage getWindowIcon() {
        try {
            return ImageIO.read(new File("data/images/icon.jpg"));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return null;
    }

    private LinkedList<PrintStream> printStreamList = new LinkedList<>();
    private DefaultListModel<MLClass> classesModel;
    private DefaultListModel<BoundingBox> bboxModel;
    private ProjectManager manager;
    private LinkedList<Rectangle> rectangles;
    private boolean clickStart;
    private BBoxJLabel bBoxLabel;
    private String checkBoxTexts[] = {"Filter per 100th iteration", "Save mAP as percentage", "Save as Excel"};
    private ImageIcon icon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classesLabel;
    private javax.swing.JList<model.elements.MLClass> classesList;
    private javax.swing.JPanel classesPane;
    private javax.swing.JScrollPane classesScollPane;
    private javax.swing.JButton createClass;
    private javax.swing.JLabel customSLabel;
    private javax.swing.JTextField customSTF;
    private javax.swing.JPanel editingPane;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JCheckBox filterCheckBox;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePathFilesMaker;
    private javax.swing.JPanel imageRenumberingTab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSplitPane labelingSplitPane;
    private javax.swing.JPanel labelingTool;
    private javax.swing.JLabel labelsLabel;
    private javax.swing.JList<BoundingBox> labelsList;
    private javax.swing.JPanel labelsPane;
    private javax.swing.JScrollPane labelsScrollPane;
    private javax.swing.JSplitPane listsSplitPane;
    private javax.swing.JLabel logFileLabel;
    private javax.swing.JTextField logFileTextField;
    private javax.swing.JTextField logFileTextField1;
    private javax.swing.JTextField logFileTextField2;
    private javax.swing.JTextField logFileTextField3;
    private javax.swing.JTextField logFileTextField4;
    private javax.swing.JPanel logParser;
    private javax.swing.JDialog newClassDialog;
    private javax.swing.JButton nextImgButton;
    private javax.swing.JLabel numberingStartLabel;
    private javax.swing.JTextField numberingStartTextField;
    private javax.swing.JButton openProjectButton;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JLabel outputFileLabel1;
    private javax.swing.JLabel outputFileLabel2;
    private javax.swing.JLabel outputFileLabel3;
    private javax.swing.JLabel outputFileLabel4;
    private javax.swing.JTextField outputTextField;
    private javax.swing.JComboBox<String> paternIndexComboBox;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JButton prevImgButton;
    private javax.swing.JLabel projectPathLabel;
    private javax.swing.JTextField projectTextField;
    private javax.swing.JComboBox<Character> seperatorComboBox;
    private javax.swing.JPanel showLabels;
    private javax.swing.JLabel speratorLabel;
    private javax.swing.JScrollPane tab01ErrScrollPane;
    private javax.swing.JTextArea tab01ErrorOutput;
    private javax.swing.JSplitPane tab01ToolsSplitPane;
    private javax.swing.JScrollPane tab02ErrScrollPane;
    private javax.swing.JTextArea tab02ErrorOutput;
    private javax.swing.JButton tab02OpenFileBt;
    private javax.swing.JButton tab02RunBt;
    private javax.swing.JScrollPane tab03ErrScrollPane;
    private javax.swing.JTextArea tab03ErrorOutput;
    private javax.swing.JButton tab03OpenRFBt;
    private javax.swing.JButton tab03OpenRFBt1;
    private javax.swing.JButton tab03OpenWFBt;
    private javax.swing.JButton tab03RunBt;
    private javax.swing.JScrollPane tab04ErrScrollPane;
    private javax.swing.JTextArea tab04ErrorOutput;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel yLabel;
    private javax.swing.JComboBox<String> yoloVerComboBox;
    // End of variables declaration//GEN-END:variables
}
